### ISSUE TITLE
Surface tension simulations become unstable

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#420]
The surface tension solver is in an experimental stage. A known issue is that simulations involving surface tension can become unstable and produce errors in the simulation that look like small pops/explosions ([Example 1](https://gfycat.com/OpulentPointlessDogfish), [Example 2](https://gfycat.com/UnselfishDefinitiveLiger)). 

At the moment, I am unsure of the cause of these stability problems, but am hoping to solve this problem before a stable release of v1.0.5! It seems that these problems occur more frequently with higher surface tension values and complex obstacle geometry, but also can happen without obstacles in the scene.

The next experimental version (v9.0.5.3 available Feb 1st) includes a change in settings to add a stability parameter for development/testing purposes. Documentation here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#surface-tension.

\- Ryan

**Comment by olejonny** [comment]
Just bought FLIP fluids and tried it on 2.8. Got error telling med that object didn't have attribute "surface_tension" when trying to bake. 2.79 is baking as we speak so that's good at least.

**Comment by rlguy** [comment]
Hi olejonny,

This type of error can happen if Blender is not restarted after installing the FLIP Fluids addon or if running a .blend file saved under a different version of Blender or FLIP Fluids.

Does this error still happen after restarting Blender and creating a new .blend file?

If you still get an error, please attach the full error message and a .blend file that reproduces this issue and I will be able look further into this. The full error message can be found in the Blender system console (**Blender > Window > Toggle System Console**) on Windows. Or by running Blender from the terminal on MacOS or Linux.

[Guidelines for Reporting Bugs and Issues](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues)

\- Ryan

**Comment by rlguy** [comment]
An update on this bug:

The unfortunate news is that I have not yet found a good solution to stop these frequent bugs in the surface tension feature. This feature has been a nightmare to implement and has been a constant source of problems over the past 6 months. I think it is time for me to stop sinking development time into salvaging this feature, admit defeat, and start over with a new surface tension simulation method.

Not all development time while trying to fix this feature has been wasted, however. Many of the recent performance improvements, and the recent particle sheeting feature, has been a side effect of trying to get surface tension to work.

I'm looking at implementing a more stable/accurate (and much faster!) method: _A Multiscale Approach to Mesh-based Surface Tension Flows_ ([video](https://youtu.be/ArxbKwJvTWs), [paper](http://pub.ist.ac.at/group_wojtan/projects/surface_tension/surface_tension.pdf)). I'll need to spend some time studying up and hitting the books to better understand this simulation tech. This will cause a  further delay in getting this feature stable and I apologize for how long this feature has taken to develop. But we'll get there eventually.

**Comment by rlguy** [comment]
Update: It looks like this issue has actually been fixed and has been testing well over the past few weeks.

The surface tension method implemented isn’t the most modern/quickest method and I would still like to implement a better method. But at least there is now a workable surface tension feature that can be used until a new method is implemented.

We will be including this fix in the next experimental version (9.0.5.4) which will be available near the end of next week.

**Comment by PavelBlend** [comment]
I noticed in version 9.0.5.5 of defects in surface tension. I set the number of substeps min = 10 max = 24:
[surface_tension_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3229335/surface_tension_test.zip)

This result was obtained in frame 44:
![0044](https://user-images.githubusercontent.com/7983249/58505877-a54ee780-8196-11e9-8f75-97bc73bb8b8c.jpg)

45 frame:
![0045](https://user-images.githubusercontent.com/7983249/58505888-ac75f580-8196-11e9-81b4-f06caf3a06ba.jpg)

And in frame 46, the simulation was restored and became stable. But then the simulation again became unstable. What makes a liquid spiked in certain frames?

**Comment by rlguy** [comment]
Hi PavelBlend,

I am not at a system where I am able to run the simulation at the moment, but I have a guess. 

You might need to run more substeps to keep the simulation stable. The surface tension 'Accuracy' setting in the world panel can be used to set a threshold of number of substeps to take and will show the number of estimated substeps that the simulator will take:

<img width="304" alt="surface_tension_substeps" src="https://user-images.githubusercontent.com/4285191/58508070-013e4f80-8148-11e9-9c30-1e4d1dabe97d.png">

This estimated number will override the minimum number of substeps if the estimation is higher. The current default accuracy is set to 90% (requiring 9 substeps for your scene), but for high surface tension simulations, you may need to increase the accuracy to keep the simulation stable enough.

\- Ryan

**Comment by PavelBlend** [comment]
The problem is that the simulation is stable at the beginning. And I thought it would be stable to the end. But when the simulation got caked, I looked at it and saw 3-4 broken frames. How to determine that the simulation will not spoil 3-4 frames? If at the beginning of the simulation, everything looked extremely stable. Or you should always use the Accuracy parameter more than 90%?

Result:
https://gfycat.com/LiveSparklingAfricangroundhornbill

**Comment by rlguy** [comment]
I just had a chance to check out the .blend file. It looks like the problem not not that the accuracy isn't high enough. The few frames are getting spoiled by a simulation explosion that could be caused by another bug. I had thought I had fixed simulation explosions like these, but it looks like there is something else that is able to trigger these types of explosions.

I'll re-open this issue and continue looking into what could be causing the problem.

**Comment by rlguy** [comment]
This issue has been fixed and will be included in the next version update (1.0.5, available by the end of next week).

The bug ended up being similar to the earlier explosions that I had thought I had fixed (numerical precision error). There was another area of code where numbers could become too small and cause problems in the accuracy of the computations. This bug would occur more frequently in simulations with higher surface tension values, high number of substeps, and smaller world scales, which is why this issue was easy to reproduce in your .blend file.

Here is an animation showing the fixed result of the fluid with improved stability: https://gfycat.com/similarshamefulindianringneckparakeet

I'll leave this issue open until we can confirm that these types of explosion issues have been fixed.

**Comment by rlguy** [comment]
This feature seems as stable as we can make it. The surface tension method has some flaws and I hope to still add an improved method in future development (_A Multiscale Approach to Mesh-based Surface Tension Flows_ ([video](https://youtu.be/ArxbKwJvTWs), [paper](http://pub.ist.ac.at/group_wojtan/projects/surface_tension/surface_tension.pdf))_).

Closing this issue. I will re-open a new issue when development begins on an improved surface tension method.

**Comment by PavelBlend** [comment]
It seems the surface tension is still not stable:
https://giant.gfycat.com/LikableTintedHatchetfish.webm
I am using version 1.0.8a.
Here is the scene:
[vine_2-82.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/4703696/vine_2-82.zip)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for let me know about this! That does look quite unstable. 

I have been testing this .blend file a few times, but have not reproduced the issue yet. Sometimes these type of issues can be random and rarely occur. Does this happen in your simulations frequently? If you re-run the simulation, does the explosion still happen?

I'll create a script to run the simulation repeatedly during the week. We actually fixed a bug recently that could potentially cause explosions, so I will test in both v1.0.8a and our current development version.

\- Ryan

**Comment by PavelBlend** [comment]
Hello, @rlguy 
I experimented with surface tension and again got unstable results:
![01](https://user-images.githubusercontent.com/7983249/109956789-1ec52380-7cf5-11eb-810b-a4c0e07624d7.jpg)
[unstable_surface_tension.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/6083216/unstable_surface_tension.zip)

OS: Win 10
FLIP Fluids: 9.0.9.15
Blender: 2.92.0 Release

**Comment by PavelBlend** [comment]
I baked the liquid a second time and the error reappeared.
![01](https://user-images.githubusercontent.com/7983249/109957915-a52e3500-7cf6-11eb-8c9c-6a7ecefb1b82.jpg)
But now it is less pronounced. The particles became more stable than in the previous case. I noticed that the particles fly away from each other. They are at such a distance that they do not affect each other. Each particle is isolated from the others.

**Comment by rlguy** [comment]
Thanks for the report and .blend file! I am able to reproduce this issue with both surface tension on and off, so this will be unrelated to surface tension instability. I think this is more related to issue #508 (Particles stuck to edges of obstacle). I'll continue this comment in that issue thread.
