### ISSUE TITLE
Particles stuck to edges of obstacle

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#508]
#### System Information

**Blender Version (including hash): 2.90.1 3e85bb34d0d7**
**FLIP Fluids Version: 1.0.9**
**Operating System: Windows 10 64 bit**
**CPU: AMD A8 5600K**
**GFX: -**
**RAM: 16 GB**

#### Describe the bug

Wrong color for debug particles. And the question is: why do particles stick to the border of the obstacle? They don't move.

#### To Reproduce

Bake the liquid from this scene:
[debug_particles_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/5683478/debug_particles_test.zip)

#### Expected Behaviour
Fixed particles should not be red.

#### Actual Behaviour
Fixed particles are colored red (this color is specified in the high_speed_particle_color parameter).

#### Screenshots

![particles_debug](https://user-images.githubusercontent.com/7983249/101990243-e6deaf00-3cb6-11eb-80fa-795212c35865.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! It looks like this could be related to issue #1. At the moment, I am not sure how to solve the issue of stuck particles, but maybe this .blend file will help find a solution. It looks like better collision handling might be a way that this could be fixed.

The reason for the high velocity particles is a side effect of how the FLIP method works where stuck particles can gain velocity/accelerate from the surrounding particles that are moving. If you set the PIC/FLIP ratio to 1.0, they wont have as high velocity but they will still stick. 

For some reason the high velocity particles are still not moving. This is something I will need to look into.

**Comment by rlguy** [comment]
Continuing from [this comment in issue #420](https://github.com/rlguy/Blender-FLIP-Fluids/issues/420#issuecomment-790543581):

> **PavelBlend**
> Hello, @rlguy
> I experimented with surface tension and again got unstable results:
> ![unstable_particles](https://user-images.githubusercontent.com/4285191/110018191-e7964880-7cdb-11eb-8df9-acfbd0a72f9b.jpg)
> [unstable_surface_tension.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/6086104/unstable_surface_tension.zip)

It looks like this instability is being caused by particles becoming stuck to the edges of the obstacle. The stuck particles are gaining high amounts of velocity and when becoming unstuck, they are causing the simulation to explode.

![stuck_particles](https://user-images.githubusercontent.com/4285191/110018374-11e80600-7cdc-11eb-9cb1-ff89e435bdff.jpg)

The highlighted particles are stuck and before releasing, they have velocities around 70 to 100m/s while the surrounding particles are around 3m/s.

A workaround can be to enable the _Remove particles with extreme velocities_ option, but I do not think this is a good solution. There are too many unstable particle for this to be acceptable and the underlying issue that is causing this should be fixed.

I am going to make this a high priority issue that needs to be fixed before the next stable release in early April.

**Comment by rlguy** [comment]
Update: I have found the cause for this issue and have a solution for a fix. I'll update this issue when the fix is available in experimental version 9.0.9.16 (10-MAR-2021) and will include a write-up on how this was fixed in our next development notes.

**Comment by rlguy** [comment]
This fix is now available in [experimental version](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Force-Field-Experimental-Builds) 9.0.9.16.

For a detailed explanation, see our [development notes # 50 here](https://flipfluids.com/weekly-development-notes-50-collision-handling-improvements/) or on our [Blender Artists thread here](https://blenderartists.org/t/flip-fluids-addon-a-liquid-fluid-simulation-tool-for-blender/702503/1115?u=rlguy).

**Comment by PavelBlend** [comment]
It looks like the particles are still not stable:
![555](https://user-images.githubusercontent.com/7983249/112021540-74e1f580-8b42-11eb-8085-5061f3588ec1.jpg)
version 9.0.9.17:
[test_water.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/6183668/test_water.zip)

**Comment by rlguy** [comment]
Thanks for the report and .blend file! I just had a chance to test it and can reproduce the issue.

It looks like the problem is that the domain resolution is too low to accurately resolve the thin walls of the obstacle. Obstacle debug view at 70 resolution:

![low_obstacle_resolution](https://user-images.githubusercontent.com/4285191/112034545-d632a600-8afb-11eb-8510-bba991ef8c42.jpg)

The thin cracks and holes like these will cause simulations to become unstable because the data around these locations are not good and are inconsistent.

The fix is to increase resolution so that the obstacle is fully resolved on the grid with better data. Here is an example at 140 resolution: 

![higher_obstacle_resolution_140](https://user-images.githubusercontent.com/4285191/112035054-6a9d0880-8afc-11eb-8e66-f78417080da9.jpg)

Let us know if you run into any other problems. We are still testing particle stability related to this issue and also with surface tension.
